osbuild/rpmrepo

repo/cs8-aarch64-appstream.json, repo/cs8-aarch64-baseos.json, repo/cs8-ppc64le-appstream.json, repo/cs8-ppc64le-baseos.json, repo/cs8-x86_64-appstream.json, repo/cs8-x86_64-baseos.json
Add repositories for CentOS Stream 8. All architectures are included (note
that s390x isn't supported by Stream 8). BaseOS and AppStream should be fine
for our needs, we might need to add RT/PowerTools later.
I chose msync.centos.org as the source, this is what the docs recommends:
https://wiki.centos.org/HowTos/CreatePublicMirrors
=> repo: add CentOS Stream 8

repo/el8-x86_64-google-cloud-sdk.json, repo/el8-x86_64-google-compute-engine.json
Add repositories for RHEL-8 x86_64 with Google Cloud Platform Guest
tools and their SDK. GCP supports only x86_64.
This is needed to generate image test cases for the new `gce-byos` image - https://github.com/osbuild/osbuild-composer/pull/1365
Signed-off-by: Tomas Hozza <thozza@redhat.com>
=> repo: Add Google Cloud Platform el8 repositories

repo/el8-aarch64-rhui-3.json, repo/el8-x86_64-ha-n8.5.json, repo/el8-x86_64-rhui-3.json
Mirror RHUI client repo for RHEL-8 and x86_64 and aarch64.
Mirror HA repo for RHEL-8.5 and x86_64.
This is required for generating image test cases in https://github.com/osbuild/osbuild-composer/pull/1607
=> Add repository definitions needed for RHEL ec2 images

repo/el8-aarch64-rhui-3.json, repo/el8-x86_64-ha-n8.5.json
`el8-x86_64-ha-n8.5` repository was mistakenly named as
`el8-x86_64-rt-n8.5`.
`el8-aarch64-rhui-3` repository was mistakenly named as
`el8-aarch64-rhui-n8.5`.
Related to #11 
Signed-off-by: Tomas Hozza <thozza@redhat.com>
=> Fix copy&paste error from PR#11

repo/el8-x86_64-ansible-2.json, repo/el8-x86_64-sap-n8.6.json, repo/el8-x86_64-saphana-n8.6.json, repo/el9-aarch64-appstream-n9.0-beta.json, repo/el9-aarch64-appstream-n9.0.json, repo/el9-aarch64-baseos-n9.0-beta.json, repo/el9-aarch64-baseos-n9.0.json, repo/el9-ppc64le-appstream-n9.0-beta.json, repo/el9-ppc64le-appstream-n9.0.json, repo/el9-ppc64le-baseos-n9.0-beta.json, repo/el9-ppc64le-baseos-n9.0.json, repo/el9-s390x-appstream-n9.0-beta.json, repo/el9-s390x-appstream-n9.0.json, repo/el9-s390x-baseos-n9.0-beta.json, repo/el9-s390x-baseos-n9.0.json, repo/el9-x86_64-appstream-n9.0-beta.json, repo/el9-x86_64-appstream-n9.0.json, repo/el9-x86_64-baseos-n9.0-beta.json, repo/el9-x86_64-baseos-n9.0.json, repo/el9-x86_64-ha-n9.0.json, repo/el9-x86_64-rt-n9.0-beta.json, repo/el9-x86_64-rt-n9.0.json, repo/el9-x86_64-sap-n9.0.json, repo/el9-x86_64-saphana-n9.0.json
- Add RHEL-8.6 repos required by EC2 SAP images
- Rename existing RHEL-9.0 snapshots to RHEL-9.0-Beta
- Add repo definitions for RHEL-9.0 GA snapshots
- Add RHEL-9.0 repos required by EC2 HA and SAP images
=> Add 8.6 and 9.0 repos for SAP images and RHEL-9.0 GA repos

repo/el8-aarch64-appstream-n8.5.json, repo/el8-aarch64-appstream-r8.5.json, repo/el8-aarch64-baseos-n8.5.json, repo/el8-aarch64-baseos-r8.5.json, repo/el8-ppc64le-appstream-n8.5.json, repo/el8-ppc64le-appstream-r8.5.json, repo/el8-ppc64le-baseos-n8.5.json, repo/el8-ppc64le-baseos-r8.5.json, repo/el8-s390x-appstream-n8.5.json, repo/el8-s390x-appstream-r8.5.json, repo/el8-s390x-baseos-n8.5.json, repo/el8-s390x-baseos-r8.5.json, repo/el8-x86_64-appstream-n8.5.json, repo/el8-x86_64-appstream-r8.5.json, repo/el8-x86_64-baseos-n8.5.json, repo/el8-x86_64-baseos-r8.5.json, repo/el8-x86_64-ha-n8.5.json, repo/el8-x86_64-ha-r8.5.json, repo/el8-x86_64-rt-n8.5.json, repo/el8-x86_64-rt-r8.5.json
The previously used URLs for nightly RHEL-8.5 repositories don't exist
any more.
Signed-off-by: Tomas Hozza <thozza@redhat.com>
=> Move from nightly to released repos for RHEL-8.5

repo/cs9-ppc64le-appstream.json
This one particular file was accidentally created with el8/cs8 IDs
=> repo: fix platform-id and snapshot-id for cs9-ppc64le-appstream

.github/workflows/scheduled-snapshots.yml
First wait for the jobs to start before going to the wait_for_jobs step, otherwise the job count starts at 0 and the action completes immediately.
----
Is it possible to test this before merging?
=> github: wait for jobs to start before waiting to finish

repo/el7-x86_64-rhui-3.json, repo/el7-x86_64-server-dotnet-r1.1.json, repo/el7-x86_64-server-extras-r7.9.json, repo/el7-x86_64-server-optional-r7.9.json, repo/el7-x86_64-server-r7.9.json, repo/el7-x86_64-server-rt-r7.9.json, repo/el7-x86_64-server-sap-r7.9.json
We want to start building RHEL 7.9 images, for this we need 7.9 snapshots.
=> repo: add RHEL 7.9 x86_64 repositories

repo/el7-x86_64-server-dotnet-r1.1.json
Need to point to the folder with the repodata.
=> repo: fix 7.9 dotnet URL

repo/el7-x86_64-server-rt-r7.9.json
=> repo: fix 7.9 server-rt url

repo/el8-x86_64-rhui-azure.json
It seems the Red Hat IT certs are not properly provisioned and all other repositories use http as well.
=> repo: use plain http for el8-x86_64-rhui-azure

.github/workflows/scheduled-snapshots.yml
Generate cloudwatch queries for failed jobs. Everyone with the ReadOnly
role has RO cloudwatch access and should be able to execute these.
Example:
```
fields @timestamp, @message
| filter @logStream = "rpmrepo-batch-snapshot-staging/default/633a7139fc894897a58ca081e98c2356"
| sort @timestamp desc
```
=> .github/scheduled-snapshots: Generate cloudwatch queries

.github/scripts/snapshot_update_pr.sh, .github/scripts/update_schutzfile.py, .github/workflows/scheduled-snapshots.yml
Fedora and fedora-modular repositories don't change so don't update them
when opening a PR with snapshot update.
I also had to switch to perl to be able to use the negative lookbehind. I don't know any better solution this is the first one I've put together with a lot of trial and error and googling. Suggestions more than welcome. This change is needed once https://github.com/osbuild/osbuild-composer/pull/2508 lands to update the snapshots correctly.
=> workflows/scheduled-snapshots: do not update relased fedora repos

repo/el7-x86_64-rhui-azure.json, repo/el8-x86_64-rhui-azure.json, repo/el9-x86_64-rhui-azure.json
The URL for the synced azure rhui packages changed and we have to follow suit.
=> repo/rhui-azure: adapt to upstream url changes

src/ctl/index.py, src/ctl/pull.py
Use context-managers for open() and popen() to silence the linter warnings in CI.
=> ctl: fix linter warnings

.github/workflows/ci-lint.yml, .github/workflows/ci-repo.yml, repo/el7-x86_64-rhui-azure.json, repo/el8-x86_64-google-cloud-sdk.json, repo/el8-x86_64-google-compute-engine.json, repo/el9-x86_64-google-cloud-sdk.json, repo/el9-x86_64-google-compute-engine.json, src/script/repo-check.py
Add a new script called `repo-check.py` which reads repository configuration files from ./repo/*.json and verifies their integrity. The script takes a list of files to parse. It always parses the respective JSON file, verifies all keys for some basic properties, and prints them to standard output.
Optionally, it also checks external URLs (in our case the Base-URL) for validity. However, this requires passing `--check-external <storage>`, to make it check URLs of the specified storage class. Since RHVPN URLs cannot be accessed from the github CI, we only check the public URLs.
=> Verify repository configuration files

repo/el8-x86_64-sap-rhui-azure.json
Note that the URL is correct, but may change since it is the RHEL-8 version not RHEL-9 as the url would imply.
=> repo: Add Azure RHUI SAP client repo

.github/workflows/scheduled-snapshots.yml
The `::set-output` command is deprecated [1] and will be dropped in 2023. Use the suggested replacement by writing into `$GITHUB_OUTPUT`.
[1] https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> ci: replace `::set-output` with `$GITHUB_OUTPUT`

repo/el7-x86_64-jbeap7.json, repo/el8-x86_64-jbeap7.json, repo/el9-x86_64-jbeap7.json
Adding new repos for building EAP images for all major RHEL versions.
See [this comment][repourls] on the [relevant ticket][ticketurl] for the source of the URLs.
[repourls]: https://issues.redhat.com/browse/COMPOSER-1504?focusedCommentId=21357327&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21357327
[ticketurl]: https://issues.redhat.com/browse/COMPOSER-1504
=> repo: add jboss EAP repos for RHEL 7, 8, and 9

.github/workflows/scheduled-snapshots.yml
If any job which is part of the scheduled batch fails, the GH action currently prints its ID and a filer for AWS Cloudwatch to find it. However this means an extra step of logging into AWS and looking for the log.
Change the GH action to print the logs for the failed job directly in the GH action log.
=> Print logs of failed snapshot jobs in the action log

repo/f35-aarch64-fedora-modular.json, repo/f35-aarch64-fedora.json, repo/f35-aarch64-updates-released-modular.json, repo/f35-aarch64-updates-released.json, repo/f35-x86_64-fedora-modular.json, repo/f35-x86_64-fedora.json, repo/f35-x86_64-updates-released-modular.json, repo/f35-x86_64-updates-released.json
F35 is EOL. The URLs for its repositories are already not available. Delete all of them.
=> Delete F35 repos, since it is EOL

repo-definitions.yaml, repo/el7-x86_64-rhui-azure.json, repo/el8-x86_64-rhui-azure.json, repo/el8-x86_64-sap-rhui-azure.json, repo/el9-x86_64-rhui-azure.json
The old URLs are not updated any more and contain very old packages.
=> Update URLs for Azure RHUI client RPM mirrors

.github/scripts/snapshot_update_pr.sh, .github/scripts/update_schutzfile.py
The update_schutzfile.py script just substitutes new dates for the old ones, which can result in incorrect snapshots if one or more of them have been removed.
This patch runs the check-snapshot script from the $REPO being modified, checking to make sure all the new snapshots are available.
If they are not, it exits with a 1. The upstream Schutzfile will need to be changed to remove the missing snapshots (or the script needs to be modified to leave them at their final date -- but that's a subject for another patch).
=> github: Check updated Schutzfile's snapshots

Makefile, gen-repos.py, repo/f37-ppc64le-fedora-modular.json, repo/f37-ppc64le-fedora.json, repo/f37-ppc64le-updates-released-modular.json, repo/f37-ppc64le-updates-released.json, repo/f37-s390x-fedora-modular.json, repo/f37-s390x-fedora.json, repo/f37-s390x-updates-released-modular.json, repo/f37-s390x-updates-released.json, repo/f38-ppc64le-fedora-modular.json, repo/f38-ppc64le-fedora.json, repo/f38-ppc64le-updates-released-modular.json, repo/f38-ppc64le-updates-released.json, repo/f38-s390x-fedora-modular.json, repo/f38-s390x-fedora.json, repo/f38-s390x-updates-released-modular.json, repo/f38-s390x-updates-released.json, repo/f39-ppc64le-branched.json, repo/f39-s390x-branched.json, repo/f40-ppc64le-rawhide.json, repo/f40-s390x-rawhide.json
This will be helpful for testing base s390x and ppc64le support in the images repository by generating manifests.
=> Fedora: snapshot ppc64le and s390x repos

gen-all-repos.py, gen-repos.py, repo-definitions.yaml, repo/eln-aarch64-appstream.json, repo/eln-aarch64-baseos.json, repo/eln-aarch64-crb.json, repo/eln-ppc64le-appstream.json, repo/eln-ppc64le-baseos.json, repo/eln-ppc64le-crb.json, repo/eln-s390x-appstream.json, repo/eln-s390x-baseos.json, repo/eln-s390x-crb.json, repo/eln-x86_64-appstream.json, repo/eln-x86_64-baseos.json, repo/eln-x86_64-crb.json
Fedora ELN is basically a rolling, version-less distribution(1).
Thus, I had to modify gen-all-repos.py to work even if the release isn't there.
gen-repos.py got a new generator just for ELN. I was thinking whether I can reuse one of the others, but since ELN is so straightforward, I decided to just create a very tiny specialized one.
(1) /etc/os-release currently specifies VERSION_ID as 40, but platform is just eln all the time. RPM's %dist macro is versioned, but this version is arbitrary because it's bumped every time a mass-rebuild is needed, see: https://fedoraproject.org/wiki/Changes/ELN_Buildroot_and_Compose#Detailed_Description
Thus, I do believe that ELN can be treated as a version-less distribution.
=> Add support for Fedora ELN repositories

README.md
DocuSaurus doesn't like indented code blocks.
=> README: Harmonize code block md syntax

.github/workflows/scheduled-snapshots.yml
Blindly bumped to the latest versions. Not sure how to test these, you'd need to trigger a snapshot using the version in the PR.
=> Fix the action warnings

repo-definitions.yaml, repo/el7-x86_64-server-updates-7.9.json
This is needed for the RHEL-7.9 AMI image.
=> Add RHEL-7.9 Server-updates repo snapshot

src/ctl/cli.py, src/ctl/enumerate_cache.py
Enumerates all thread indices and stores it under `data/thread/meta/cache.json`
---
We can then add support for this to https://github.com/osbuild/containers/blob/main/src/scripts/rpmrepo-snapshot.sh, and trigger this as a batch job in the scheduled-snapshots workflow.
=> src/ctl: add command to build snapshots cache

src/ctl/cli.py, src/gateway/lambda_function.py
Forgot to add the command to the arg parser, and the gateway should serve the cache if it's present. If the cache is out of date and failing to generate, we can always remove it manually.
=> src: enumerate cache

.github/scripts/snapshot_update_pr.sh, .github/workflows/scheduled-snapshots.yml
The PRs will now always be opened regardless of the check-snapshot, but with the following body:
```
Results of the snapshot jobs:
Job(s) succeeded: $JOBS_SUCCEEDED
Job(s) failed: $JOBS_FAILED
If these are false, rebuild the enumerate cache manually:
Enumerate cache job succeeded: $ENUMERATE_CACHE_SUCCEEDED
Check snapshot succeeded: $CHECK_SNAPSHOT_SUCCEEDED
Workflow run: https://github.com/osbuild/rpmrepo/actions/runs/$WORKFLOW_RUN
```
This way the snapshots aren't thrown away, we can still just close the PR, and we can rebuild the cache manually if that's the only part that went wrong.
=> Scheduled snapshots cache

.github/workflows/scheduled-snapshots.yml
The '> out' was on a separate line from the command without a '\' on the previous line, so out.json was always empty.
See https://github.com/osbuild/rpmrepo/actions/runs/10397209645/job/28792528624 for failure.
Currently running a snapshot job on this branch: https://github.com/osbuild/rpmrepo/actions/runs/10452286390/job/28940408904
EDIT: IT WORKS!
=> github/scheduled-snapshots: fix output redirect

Makefile, src/gateway/lambda_function.py
Does this make sense if just surfing to
https://rpmrepo.osbuild.org/
(what also crawlers do), this should result in something other than a 4xx error?
like redirecting to the documentation what rpmrepo actually is?
=> gateway/lambda_function: redirect to documentation for crawlers

repo-definitions.yaml, repo/el7-x86_64-jbeap7.json, repo/el7-x86_64-rhui-3.json, repo/el7-x86_64-rhui-azure.json, repo/el7-x86_64-server-dotnet-r1.1.json, repo/el7-x86_64-server-extras-r7.9.json, repo/el7-x86_64-server-updates-7.9.json, repo/el8-aarch64-rhui-3.json, repo/el8-x86_64-jbeap7.json, repo/el8-x86_64-rhui-3.json, repo/el8-x86_64-rhui-azure.json, repo/el8-x86_64-sap-rhui-azure.json, repo/el9-aarch64-rhui-4.json, repo/el9-x86_64-jbeap7.json, repo/el9-x86_64-rhui-4.json, repo/el9-x86_64-rhui-azure.json, repo/el9-x86_64-sap-rhui-azure.json, repo/f39-aarch64-fedora.json, repo/f39-aarch64-updates-released.json, repo/f39-ppc64le-fedora.json, repo/f39-ppc64le-updates-released.json, repo/f39-s390x-fedora.json, repo/f39-s390x-updates-released.json, repo/f39-x86_64-fedora.json, repo/f39-x86_64-updates-released.json
- Replace download.*.bos.redhat.com -> download.devel.redhat.com
- Don't snapshot EOL Fedora 39
=> Update internal RH repo URLs and don't snapshot EOL F39

.github/scripts/test_update_schutzfile.py, .github/scripts/update_schutzfile.py, .github/workflows/ci-lint.yml, .github/workflows/ci-repo.yml
Do not assume that snapshot jobs always succeed. Validate any proposed
update to snapshot against the snapshots that actually exist. This
avoids proposing missing snapshots.
Group repository updates by distro:arch, so that snapshots from
different dates aren't mixed.
---
I renamed the repo configuration check so it also reflects the fact that it's testing github scripts. It succeeded on previous runs.
=> Rework schutzfile updates

repo-definitions.yaml, repo/el7-x86_64-rhui-4.json
Snapshotting the repo has been failing, because there are no more any new builds of RHUI client RPMs for RHEL-7.
=> RHEL-7: stop snapshotting RHUI client repo

repo-definitions.yaml
These are now available, so we can snapshot them and use for testing, instead of RHEL-9 rpms.
I noticed that we are still using el9 snapshots in el10 test repos in composer, while updating those that are already GA.
=> Snapshot RHEL-10 RHUI-4 repos

src/ctl/pull.py
dnf5 reposync times out on very large repositories like fedora
updates. It is simply too slow, causing the snapshot workflow to time
out after 6 hours.
=> src/pull: use dnf4 to sync repositories

repo-definitions.yaml, repo/el10-x86_64-google-cloud-sdk.json, repo/el8-x86_64-google-cloud-sdk.json, repo/el9-x86_64-google-cloud-sdk.json
We do not install any packages by default from these repos for our base image definitions, so we do not need to snapshot them for CI purposes.
=> Don't snaposhot Google cloud SDK repositories
