osbuild/rpmrepo

- repo/el9-aarch64-rhui-4.json
- repo/el9-x86_64-rhui-4.json
Signed-off-by: Tomas Hozza <thozza@redhat.com>
> Add RHUI-4 for RHEL-9 repo definitions

- .github/workflows/scheduled-snapshots.yml
> .github: add workflow_dispatch to snapshotting workflow

- .github/workflows/scheduled-snapshots.yml
> .github: Fewer newlines

- .github/workflows/scheduled-snapshots.yml
https://github.com/osbuild/rpmrepo/runs/5014968544 submitted the job but exited a little early. I'll just open the PR manually.
> Scheduled snapshots

- repo/el9-aarch64-appstream-n9.0-beta.json
- repo/el9-aarch64-baseos-n9.0-beta.json
- repo/el9-ppc64le-appstream-n9.0-beta.json
- repo/el9-ppc64le-baseos-n9.0-beta.json
- repo/el9-s390x-appstream-n9.0-beta.json
- repo/el9-s390x-baseos-n9.0-beta.json
- repo/el9-x86_64-appstream-n9.0-beta.json
- repo/el9-x86_64-baseos-n9.0-beta.json
- repo/el9-x86_64-rt-n9.0-beta.json
> repo: remove EL9 Beta

- repo/cs8-aarch64-powertools.json
- repo/cs8-ppc64le-powertools.json
- repo/cs8-x86_64-powertools.json
This repo is needed for mockbuild.
> repo: add PowerTools for centos-stream-8

- repo/el9-x86_64-rhui-azure.json
Need for RHEL 9.0 Azure RHUI images.
> repo: add azure rhui for el9

- repo/el7-x86_64-rhui-azure.json
Need for RHEL 7.9 Azure RHUI images.
> repo: add azure rhui for el7

- repo/el7-x86_64-eng-rhel.json
We need some internal packages for the el7 build root.
> repo: add eng-rhel for el7

- repo/f36-aarch64-fedora-modular.json
- repo/f36-aarch64-fedora.json
- repo/f36-aarch64-updates-released-modular.json
- repo/f36-aarch64-updates-released.json
- repo/f36-x86_64-fedora-modular.json
- repo/f36-x86_64-fedora.json
- repo/f36-x86_64-updates-released-modular.json
- repo/f36-x86_64-updates-released.json
- repo/f37-aarch64-rawhide-modular.json
- repo/f37-aarch64-rawhide.json
- repo/f37-x86_64-rawhide-modular.json
- repo/f37-x86_64-rawhide.json
Inspired by https://github.com/osbuild/rpmrepo/commit/bdad27b9b78faafecc5010eb5e8412b271a5e8b0
> repo: add Fedora 36 stable and Fedora 37 rawhide

- repo/el8-aarch64-appstream-n8.9.json
- repo/el8-aarch64-baseos-n8.9.json
- repo/el8-aarch64-crb-n8.9.json
- repo/el8-ppc64le-appstream-n8.9.json
- repo/el8-ppc64le-baseos-n8.9.json
- repo/el8-s390x-appstream-n8.9.json
- repo/el8-s390x-baseos-n8.9.json
- repo/el8-x86_64-appstream-n8.9.json
- repo/el8-x86_64-baseos-n8.9.json
- repo/el8-x86_64-crb-n8.9.json
- repo/el8-x86_64-ha-n8.9.json
- repo/el8-x86_64-rt-n8.9.json
- repo/el8-x86_64-sap-n8.9.json
- repo/el8-x86_64-saphana-n8.9.json
- repo/el9-aarch64-appstream-n9.3.json
- repo/el9-aarch64-baseos-n9.3.json
- repo/el9-aarch64-crb-n9.3.json
- repo/el9-ppc64le-appstream-n9.3.json
- repo/el9-ppc64le-baseos-n9.3.json
- repo/el9-s390x-appstream-n9.3.json
- repo/el9-s390x-baseos-n9.3.json
- repo/el9-x86_64-appstream-n9.3.json
- repo/el9-x86_64-baseos-n9.3.json
- repo/el9-x86_64-crb-n9.3.json
- repo/el9-x86_64-ha-n9.3.json
- repo/el9-x86_64-rt-n9.3.json
- repo/el9-x86_64-sap-n9.3.json
- repo/el9-x86_64-saphana-n9.3.json
> Add RHEL-8.9 and RHEL-9.3 nightly repo definitions

- .github/workflows/scheduled-snapshots.yml
Add the osbuild/images repository scheduled-snapshots workflow.
> github: update schutzfile for images repo

- gen-repos.py
- repo-definitions.yaml
- repo/f39-aarch64-branched-modular.json
- repo/f39-x86_64-branched-modular.json
- repo/f40-aarch64-rawhide-modular.json
- repo/f40-x86_64-rawhide-modular.json
See https://fedoraproject.org/wiki/Changes/RetireModularity
> remove modular in F39 and higher

- repo-definitions.yaml
- repo/el9-aarch64-appstream-n9.4.json
- repo/el9-aarch64-baseos-n9.4.json
- repo/el9-aarch64-crb-n9.4.json
- repo/el9-ppc64le-appstream-n9.4.json
- repo/el9-ppc64le-baseos-n9.4.json
- repo/el9-s390x-appstream-n9.4.json
- repo/el9-s390x-baseos-n9.4.json
- repo/el9-x86_64-appstream-n9.4.json
- repo/el9-x86_64-baseos-n9.4.json
- repo/el9-x86_64-crb-n9.4.json
- repo/el9-x86_64-ha-n9.4.json
- repo/el9-x86_64-rt-n9.4.json
- repo/el9-x86_64-sap-n9.4.json
- repo/el9-x86_64-saphana-n9.4.json
> Snapshot 9.4 nightly

- repo-definitions.yaml
- repo/el9-x86_64-sap-rhui-azure.json
- repo/f40-aarch64-branched.json
- repo/f40-ppc64le-branched.json
- repo/f40-s390x-branched.json
- repo/f40-x86_64-branched.json
- repo/f41-aarch64-rawhide.json
- repo/f41-ppc64le-rawhide.json
- repo/f41-s390x-rawhide.json
- repo/f41-x86_64-rawhide.json
> branch F40; add F41

- repo-definitions.yaml
- repo/el8-x86_64-base-sap-rhui-azure.json
This repository contains the RHUI client for RHEL 8.10.
See SPSTRAT-263 and COMPOSER-2254
> New repository configuration: el8 base-sap-rhui-azure

- src/gateway/lambda_function.py
Am I right, that there is no need to index this, as the majority of of the pages are not public anyway?
This would reduce our error messages e.g. in the google search console.
> gateway/lambda_function: implement robots.txt

- .github/scripts/snapshot_update_pr.sh
Not sure about this one, could make it too noisy, but could be nice not to have to click to the workflow.
---
> snapshot_update_pr: add update_schutzfile output to PR body

- repo-definitions.yaml
- repo/f43-aarch64-branched.json
- repo/f43-ppc64le-branched.json
- repo/f43-s390x-branched.json
- repo/f43-x86_64-branched.json
- repo/f44-aarch64-rawhide.json
- repo/f44-ppc64le-rawhide.json
- repo/f44-s390x-rawhide.json
- repo/f44-x86_64-rawhide.json
~Draft: Merge on or after 12 Aug.~
https://fedorapeople.org/groups/schedule/f-43/f-43-all-tasks.html
> Switch F43 to development and add F44 as rawhide

- src/gateway/lambda_function.py
The bucket is empty apart from some test data, so let's just rip it out completely, so we can delete it altogether.
> gateway: drop support for the anon storage

- gen-all-repos.py
- gen-repos.py
- repo-definitions.yaml
- repo/el8-aarch64-appstream-r8.4.json
- repo/el8-aarch64-baseos-r8.4.json
- repo/el8-ppc64le-appstream-r8.4.json
- repo/el8-ppc64le-baseos-r8.4.json
- repo/el8-s390x-appstream-r8.4.json
- repo/el8-s390x-baseos-r8.4.json
- repo/el8-x86_64-appstream-r8.4.json
- repo/el8-x86_64-baseos-r8.4.json
- repo/el8-x86_64-ha-e8.4.json
- repo/el8-x86_64-ha-r8.4.json
- repo/el8-x86_64-rt-e8.4.json
- repo/el8-x86_64-rt-r8.4.json
- repo/el8-x86_64-sap-e8.4.json
- repo/el8-x86_64-sap-r8.4.json
- repo/el8-x86_64-sap-solutions-e8.4.json
- repo/el8-x86_64-saphana-r8.4.json
I finally figured out that we modify the repositories through python scripts now :duck:
> all 8.4 eus repositories

- repo-definitions.yaml
- repo/el10-x86_64-google-cloud-sdk.json
- repo/el10-x86_64-google-compute-engine.json
> Snapshot GCP el10 repos
